export let USERS = [
  {
    id: 1,
    name: "Lan Hoang",
    age: 26,
    face: "assets/images/user/1.jpg",
    images: [
      "assets/images/user/1.jpg",
      "assets/images/user/1a.jpeg",
      "assets/images/user/1b.jpeg",
      "assets/images/user/1c.jpeg",
    ],
    state: "Hanoi",
    isLiked: false,
    isFaved: false,
    about: "Let's meet, bla, bla",
    distance: 2,
    height: 168,
    weight: 48,
    zodiac: "Aquarius",
    job: "Officer",
    relationship: "In a open relationship"
  },
  {
    id: 2,
    name: "Lieu Ngoc",
    age: 25,
    face: "assets/images/user/2.jpg",
    state: "Hanoi",
    isLiked: false,
    isFaved: false,
    about: "Let's meet, bla, bla",
    distance: 2,
    height: 168,
    weight: 48,
    zodiac: "Aquarius",
    job: "Officer",
    relationship: "In a open relationship"
  },
  {
    id: 3,
    name: "Salina Chen",
    age: 25,
    face: "assets/images/user/3.jpg",
    state: "Hanoi",
    isLiked: false,
    isFaved: false,
    about: "Let's meet, bla, bla",
    distance: 2,
    height: 168,
    weight: 48,
    zodiac: "Aquarius",
    job: "Officer",
    relationship: "In a open relationship"
  },
  {
    id: 4,
    name: "Cam Nhung Nguyen",
    age: 25,
    face: "assets/images/user/4.jpg",
    state: "Hanoi",
    isLiked: false,
    isFaved: false,
    about: "Let's meet, bla, bla",
    distance: 2,
    height: 168,
    weight: 48,
    zodiac: "Aquarius",
    job: "Officer",
    relationship: "In a open relationship"
  },
  {
    id: 5,
    name: "Can Chi",
    age: 25,
    face: "assets/images/user/5.jpg",
    state: "Hanoi",
    isLiked: false,
    isFaved: false,
    about: "Let's meet, bla, bla",
    distance: 2,
    height: 168,
    weight: 48,
    zodiac: "Aquarius",
    job: "Officer",
    relationship: "In a open relationship"
  },
  {
    id: 6,
    name: "Dang Thu Thao",
    age: 25,
    face: "assets/images/user/6.jpg",
    state: "Hanoi",
    isLiked: false,
    isFaved: false,
    about: "Let's meet, bla, bla",
    distance: 2,
    height: 168,
    weight: 48,
    zodiac: "Aquarius",
    job: "Officer",
    relationship: "In a open relationship"
  },
  {
    id: 7,
    name: "Nguyen Thuy Duong",
    age: 25,
    face: "assets/images/user/7.jpg",
    state: "Hanoi",
    isLiked: false,
    isFaved: false,
    about: "Let's meet, bla, bla",
    distance: 2,
    height: 168,
    weight: 48,
    zodiac: "Aquarius",
    job: "Officer",
    relationship: "In a open relationship"
  },
  {
    id: 8,
    name: "Hoang Ha Phuong",
    age: 25,
    face: "assets/images/user/8.jpg",
    state: "Hanoi",
    isLiked: false,
    isFaved: false,
    about: "Let's meet, bla, bla",
    distance: 2,
    height: 168,
    weight: 48,
    zodiac: "Aquarius",
    job: "Officer",
    relationship: "In a open relationship"
  }
]
